add batching to presigned url requests
Garden-AI/garden pull request #198
Opened 2023-07-06 20:48 UTC by isaac-darling

`Fixes #193 `

## Overview

Switches the request structure during loading to employ batching to reduce http overhead.

## Discussion

Requires the corresponding [backend PR](https://github.com/Garden-AI/garden-backend/pull/35).

## Testing

Cannot be fully tested until the aforementioned backend PR is merged.

2023-07-06 21:03 UTC, isaac-darling commented
As expected, `mypy` is not a fan of this structure. I leave it to the reviewer to decide whether or not that is important. (yes the tests will fail without making an exception, but is the behavior worth an exception?)

2023-07-07 18:51 UTC, WillEngler requested changes
I think the singular/plural stuff is confusing and a little more involved than it needs to be. I left some suggestions on interface changes that I think could make it easier to follow and implement

2023-07-13 18:43 UTC, WillEngler reviewed
Awesome, this is almost there

2023-07-13 18:43 UTC, WillEngler commented on garden_ai/backend_client.py
>      def _get_presigned_url(
nit: this takes multiple model names so the helper method should be plural

2023-07-13 18:43 UTC, WillEngler commented on garden_ai/client.py
> +                )
Not a blocker, but I feel like there's a more straightforward way to express this.

2023-07-13 19:50 UTC, WillEngler approved these changes
LGTM!

2023-07-13 20:30 UTC, merged