Will/content type header kludge
Garden-AI/garden pull request #80
Opened 2023-03-13 19:53 UTC by WillEngler

2023-03-13 22:13 UTC, WillEngler commented on .github/workflows/ci.yaml
> +          safety check
Newer version of MLFlow client uses newer version of SQLAlchemy, so we're not triggering warning 51668 any more.

2023-03-14 17:46 UTC, OwenPriceSkelly requested changes

2023-03-14 17:46 UTC, OwenPriceSkelly commented on garden_ai/mlflow_bandaid/binary_header_provider.py
> +    def in_context(self):
I think we should add something to a docstring that gives a little context for the hack like a link to a relevant issue upstream (maybe even just a summary of or link to your slack thread with ben g), partly for like our own sake but more for contributors who might be confused/alarmed by a `mlflow_bandaid` module

2023-03-14 17:46 UTC, OwenPriceSkelly commented on garden_ai/mlflow_bandaid/binary_header_provider.py
> +    def in_context(self):
something like the `garden_json_encoder` docstring in utils

2023-03-14 19:04 UTC, WillEngler commented on garden_ai/mlflow_bandaid/binary_header_provider.py
> +    def in_context(self):
Good suggestions. I added more context and issue links.

2023-03-14 19:05 UTC, OwenPriceSkelly approved these changes

2023-03-14 19:07 UTC, merged